name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag driver-alertness-analysis:$(date +%s)
    
    - uses: actions/checkout@v1
    - name: Push the Docker image
      run: docker push anujkapil/driver-alertness-analysis:$(date +%s)
